### ISSUE TITLE
Enchancement: edit an existing case when surveying

### ISSUE THREAD

**Issue by severinmenard** [kobotoolbox/kobotoolbox.org#19]
Not sure whether it is the right place for improvement requests. 
Interested about this new feature proposal: https://docs.google.com/document/d/1svCWjnn4cWhAugK-fKb3owMUZb2DkG8t_w7vpwHIoPM/edit#!
Is there any plan to upgrade KBT this way?

**Comment by jnm** [comment]
Please do raise these questions on the forum:
https://community.kobotoolbox.org/t/update-an-already-submitted-record-on-a-mobile-client/1745

If you or anyone / any organization you know can contribute to the development of the feature, please include that information on your forum post. Thank you!
