### ISSUE TITLE
Add WB logo 

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobotoolbox.org#43]
We need to add the World Bank logo to our group of supporters. Logo may need to be inverted to white similar to OCHA/UNHCR and made transparent.

![WB_LOGO](https://user-images.githubusercontent.com/673511/88847873-abcf5980-d1b5-11ea-85fd-e955348497a0.jpg)

**Comment by jnm** [comment]
[here's a vector version](https://github.com/kobotoolbox/kobotoolbox.org/files/5037663/theworldbank.eps.zip)
