### ISSUE TITLE
Replace current opening photo

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobotoolbox.org#47]
The background picture is very dated, it's a phone from about 2009... 

![image](https://user-images.githubusercontent.com/673511/90897637-7290a080-e393-11ea-9d9a-d34e7ffbd5e3.png)

**Comment by Ig-Rebollo** [comment]
@tinok @magicznyleszek I photoshoped screenshots of the app in one of the copyright-free pictures Leszek found on Unsplash. Because it was not set up to superimpose images I had to fiddle with it quite a bit and it might still be a bit noticeable that it is not a real photo. If you think it's good enough we can switch it already, otherwise I can take a picture of my wife using the app in the same position than the one currently online.

![image](https://user-images.githubusercontent.com/22472326/91078806-2c487500-e611-11ea-97b2-4fb3f0653dd9.png)

Here the [link to the original in GDrive](https://drive.google.com/file/d/1Dep3EBR6ovgOAvL7wHMIS4JHi6cD5nTp/view?usp=sharing)

**Comment by tinok** [comment]
@Ig-Rebollo I think the layout looks good. For the laptop screen I'd prefer a different image, like the auto report, the table, or the map. Maybe hide the bookmarks bar :) We also need a good title that's not "Test survey..."

The mobile image should be a form being filled rather than the start screen, as in the current home page. There seems to be too little whitespace around the buttons, I think there's more of a margin at the left and right in the real app.

**Comment by Ig-Rebollo** [comment]
@tinok @magicznyleszek I took [this picture](https://drive.google.com/file/d/1E2a60hRXCy_Qm5FZE-cyfvFpzqHQK68f/view?usp=sharing) following a similar layout. Incorporated some of the elements you mentioned Tino, however the only screenshot I had of the KoBo Collect app still says 'Test survey' on the title. I'll try to find an Android phone to take new screenshots and repeat the photo, but let me know if you already have some KoBoCollect screenshots I can use.

**Comment by Ig-Rebollo** [comment]
@tinok @magicznyleszek Made a few new versions with better screenshots (thanks to John) and the help of my wife Jennie who very kindly accepted to pose. Here are 3 options to choose from:

Option 1
![image](https://user-images.githubusercontent.com/22472326/91609054-aeec6f80-e944-11ea-976b-50aa3c0ea7e1.png)

Option 2
![image](https://user-images.githubusercontent.com/22472326/91609114-cd526b00-e944-11ea-8864-c4e96e4a4e53.png)

Option 3
![image](https://user-images.githubusercontent.com/22472326/91609135-d8a59680-e944-11ea-86c6-e30d6f2fb09f.png)

Alternatively, I can go back to the Unsplash picture and I Photoshop the screenshots into it, however as you saw, it never looks as natural (my Photoshop skills are pretty good, but not _that_ good).

You can find the high resolution version of these 3 pictures in the Google Drive folder: https://drive.google.com/drive/u/3/folders/0B-dl8bGmDrKkN01SRFNJRkhLQWc

**Comment by magicznyleszek** [comment]
@tinok @Ig-Rebollo I really like your pictures, no need to use Unsplash :) I've checked all three options:

Option 1:
<img width="1440" alt="Screenshot 2020-09-07 at 17 05 25" src="https://user-images.githubusercontent.com/2521888/92400820-d0134400-f12c-11ea-868b-6abcae31a3f1.png">

Option 2:
<img width="1440" alt="Screenshot 2020-09-07 at 17 05 47" src="https://user-images.githubusercontent.com/2521888/92400835-d6092500-f12c-11ea-870e-df041d910307.png">

Option 3:
<img width="1440" alt="Screenshot 2020-09-07 at 17 06 05" src="https://user-images.githubusercontent.com/2521888/92400846-da354280-f12c-11ea-9294-526b860be76c.png">

I'm leaning towards **Option 1** with second choice being **Option 3**. Maybe we could use both of them - loading them randomly on page load?

**Comment by tinok** [comment]
@magicznyleszek Thanks for mocking this up. Let's go with option 3!
